#!/usr/bin/env bash
# =============================================================================
# homelab_2026.1 - Generate terraform.tfvars
# =============================================================================
# Purpose
#   Generates terraform.tfvars for a chosen environment from generated config files.
#   This keeps secrets out of git and makes Terraform usage low-friction.
#
# Inputs
#   - generated_configs/homelab.env (non-secret)
#   - generated_configs/.env        (contains PVE token secret)
#
# Usage
#   scripts/gen_tfvars.sh dev
#   scripts/gen_tfvars.sh prod
# =============================================================================

set -Eeuo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd -P)"

# shellcheck disable=SC1091
source "${REPO_ROOT}/scripts/lib/config.sh"

main() {
  local env_name="${1:-dev}"
  case "${env_name}" in
    dev|prod) ;;
    *) die "Environment must be dev or prod" ;;
  esac

  log_init
  config_load_exports

  local secret_env="${REPO_ROOT}/generated_configs/.env"
  [[ -f "${secret_env}" ]] || die "Missing ${secret_env}. Run Proxmox API token bootstrap first."

  # shellcheck disable=SC1090
  set -a
  source "${secret_env}"
  set +a

  local endpoint="https://${PROXMOX_HOST}:${PROXMOX_PORT:-8006}/api2/json"
  local api_token="${PVE_TOKEN_ID}=${PVE_TOKEN_SECRET}"

  local out_dir="${REPO_ROOT}/terraform/environments/${env_name}"
  local out_file="${out_dir}/terraform.tfvars"

  cat >"${out_file}" <<EOFV
# Generated by scripts/gen_tfvars.sh on $(date -Iseconds)
# Do not commit this file.

proxmox_endpoint  = "${endpoint}"
proxmox_api_token = "${api_token}"
proxmox_insecure  = false
proxmox_node_name = "${PROXMOX_NODE}"
EOFV

  chmod 600 "${out_file}" || true
  log_ok "Wrote ${out_file}"
}

main "$@"
